# Generated by Django 5.2.7 on 2025-10-09 00:34

import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_message_options_message_edited_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('unread', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_sender__3d379c_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_parent__030394_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'read'], name='messaging_m_receive_6da6d1_idx'),
        ),
    ]
